server:
  port: 8888  # RESTful API

grpc:
  server:
    host: localhost
    port: 50051  # gRPC

spring:
  application:
    name: security-grpc-server
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${properties.datasource.url}
    username: ${properties.datasource.username}
    password: ${properties.datasource.password}
  redis:
    host: localhost
    port: 16379
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true


secret: ${properties.secret}
